# Chapter 4 Inner Products in the Euclidean Vector Spaces

Let us investigate the inner products and projections in $\mathbf{R}^n$.

In [24]:
# numerical and scientific computing libraries  
import numpy as np 
import scipy as sp

# plotting libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
# for pretty printing
np.set_printoptions(4, linewidth=100, suppress=True)

### Standard inner product or dot product in $\mathbb{R}^n$.

For two Euclidean vectors $\mathbf{x}, \mathbf{y} \in \mathbb{R}^n$, we define the standard inner product or dot product as
$$<\mathbf{x}, \mathbf{y}> = \mathbf{x}^\top \mathbf{y} = \sum_{i=1}^n x_i y_i$$
Even though there are infinitely many inner products, as we have seen in the textbook, the standard inner product is a special one, on which our most numerics on the length and angle on the earth are based. Probably you might already encountered this concept (partially at least).

In [26]:
# Setting dimension
n = 10

In [14]:
# two vectors generated randomly
a = np.random.randn(n)
b = np.random.randn(n)
print('a = ',a)
print('b = ',b)
# many ways of computing the dot product
ip1 = np.inner(a,b)
ip2 = np.dot(a,b)
ip3 = np.sum(a[:]*b[:])
ip4 = sum(a[:]*b[:])
# In principle, all these produce a single value. Be careful in using np.inner and np.dot when a and b are multi-dimensional.
print(ip1, ip2, ip3, ip4)

a =  [ 0.2506  1.724   0.0263 -1.3574 -0.069   0.4646 -0.019   0.5525  0.4205  0.1339]
b =  [ 0.6913  1.3343 -1.2427 -2.0197 -0.0814  0.5488  0.2315  0.2116 -0.3749 -1.0132]
5.262119626186437 5.262119626186437 5.262119626186438 5.262119626186438


For a given inner product $<\cdot,\cdot>$, the associated norm of a vector $\mathbf{v}$ is defined as $|\mathbf{v}| = \sqrt{<\mathbf{v}, \mathbf{v}>}$. With the standard inner product, its norm or length is $|\mathbf{x}| = \sqrt{\mathbf{x}^\top \mathbf{x}}$.

In [15]:
# Define a norm for standard inner product
def norm_scratch(v):
    return np.sqrt(sum(v**2))

print('|a| = ', norm_scratch(a), np.linalg.norm(a))
# normalize a vector
c = (1/norm_scratch(a))*a
print('|c| = ', norm_scratch(c))

|a| =  2.3662469061019555 2.3662469061019555
|c| =  1.0


### One-dimensional projection

Now consider a one-dimensional projection along a vector $\mathbf{v}$.

In [16]:
v1 = np.random.randn(n)
norm_v1 = norm_scratch(v1)
v = (1/norm_v1)*v1

#check the unity of v
print(norm_scratch(v))

# project vector a along the direction of v
c1 = np.inner(a,v)
a_proj = c1*v
cosine = c1/norm_scratch(a)
print('angle = ', np.degrees(np.arccos(cosine)))

print('a      = ', a)
print('v      = ', v)
print('c1 = ', c1)
print('a_proj = ',a_proj)

1.0
angle =  86.34342164058197
a      =  [ 0.2506  1.724   0.0263 -1.3574 -0.069   0.4646 -0.019   0.5525  0.4205  0.1339]
v      =  [ 0.1446  0.2922 -0.2067  0.1501 -0.0684 -0.0554  0.636   0.1971 -0.4901 -0.3704]
c1 =  0.15090980728458506
a_proj =  [ 0.0218  0.0441 -0.0312  0.0227 -0.0103 -0.0084  0.096   0.0297 -0.074  -0.0559]


### Gram-Schmidt procedure



In [17]:
# Setting dimension
n = 10

In [18]:
a1 = np.random.randn(n)
a2 = np.random.randn(n)
a3 = np.random.randn(n)

# the first orthonormal vector
v1 = (1/norm_scratch(a1))*a1

# the second orthonormal vector
v = a2 - np.inner(a2,v1)*v1
v2 = (1/norm_scratch(v))*v

# the third orthonormal vector
v = a3 - np.inner(a3,v1)*v1 - np.inner(a3,v2)*v2
v3 = (1/norm_scratch(v))*v

# build a matrix of orthonormal vectors
Q = np.stack((v1,v2,v3),axis=1)

print(Q)
print(Q.T @ Q)  # As you expect, it is an identity matrix of 3x3
print(Q @ Q.T)  # It is meaningless matrix of 10x10

[[ 0.3666 -0.6032 -0.3203]
 [-0.3689  0.0236 -0.2551]
 [ 0.0309  0.0047  0.2778]
 [ 0.1253  0.1922  0.4992]
 [-0.2509 -0.3002 -0.3623]
 [ 0.4524  0.4613 -0.4236]
 [ 0.3192  0.1958 -0.2265]
 [ 0.3405 -0.4416  0.1812]
 [ 0.3617  0.1774 -0.0982]
 [ 0.3109 -0.1758  0.3185]]
[[ 1. -0. -0.]
 [-0.  1. -0.]
 [-0. -0.  1.]]
[[ 0.6008 -0.0678 -0.0805 -0.2299  0.2051  0.0233  0.0714  0.3332  0.0571  0.118 ]
 [-0.0678  0.2017 -0.0821 -0.169   0.1779 -0.0479 -0.0553 -0.1823 -0.1042 -0.2001]
 [-0.0805 -0.0821  0.0782  0.1435 -0.1098 -0.1015 -0.0521  0.0588 -0.0153  0.0973]
 [-0.2299 -0.169   0.1435  0.3019 -0.27   -0.0661 -0.0354  0.0482  0.0304  0.1642]
 [ 0.2051  0.1779 -0.1098 -0.27    0.2843 -0.0985 -0.0568 -0.0185 -0.1084 -0.1406]
 [ 0.0233 -0.0479 -0.1015 -0.0661 -0.0985  0.5969  0.3306 -0.1264  0.2871 -0.0754]
 [ 0.0714 -0.0553 -0.0521 -0.0354 -0.0568  0.3306  0.1915 -0.0188  0.1724 -0.0073]
 [ 0.3332 -0.1823  0.0588  0.0482 -0.0185 -0.1264 -0.0188  0.3438  0.027   0.2412]
 [ 0.0571 -0.1042 -

If dimension is 3, we can visualize the orthogonalization.

In [19]:
# Example for 3D visualization (if n=3)
if n==3:
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    # Plot original vectors
    ax.quiver(0, 0, 0, a1[0], a1[1], a1[2], color='r', label='a1')
    ax.quiver(0, 0, 0, a2[0], a2[1], a2[2], color='g', label='a2')
    ax.quiver(0, 0, 0, a3[0], a3[1], a3[2], color='b', label='a3')

    # Plot orthonormal vectors
    ax.quiver(0, 0, 0, v1[0], v1[1], v1[2], color='c', label='v1 (orthonormal)')
    ax.quiver(0, 0, 0, v2[0], v2[1], v2[2], color='m', label='v2 (orthonormal)')
    ax.quiver(0, 0, 0, v3[0], v3[1], v3[2], color='y', label='v3 (orthonormal)')

    ax.set_xlim([-2, 2])
    ax.set_ylim([-2, 2])
    ax.set_zlim([-2, 2])
    ax.legend()
    plt.show()

Let us project an arbitrary vector onto the 3-dimensional subspace spanned by a1, a2, and a3. There are two ways: the first one is projecting via the orthonormal basis; the second one is through the projection matrix $P = A (A^\top A)^{-1}A^\top$. Let us see whether they provide us a same projected vector.

In [20]:
a = np.random.randn(n)
print('a = ', a)
a_proj = np.inner(a,v1)*v1 + np.inner(a,v2)*v2 + np.inner(a,v3)*v3
print('a_proj = ', a_proj)

A = np.stack((a1,a2,a3),axis=1)
P = A @ np.linalg.inv(A.T @ A) @ A.T
a_proj1 = P @ a
print('a_proj1 = ', a_proj1)

np.allclose(a_proj, a_proj1)

a =  [-1.4286 -1.2    -0.1019  1.041   1.6794  0.0695  0.6013  0.5564  0.3964  0.8736]
a_proj =  [-0.3081 -0.3682  0.2438  0.5339 -0.516   0.0181  0.0269  0.1485  0.145   0.3408]
a_proj1 =  [-0.3081 -0.3682  0.2438  0.5339 -0.516   0.0181  0.0269  0.1485  0.145   0.3408]


True

Let us cross-check whether the common residual vector is perpendicular to a1, a2, and a3. 

In [21]:
a_res = a - a_proj
print(A.T @ a_res)

[-0.  0. -0.]


For $n > 3$, let us go further to find a orthonormal basis of $\mathbb{R}^n$. In the textbook, three vectors can not span $\mathbb{R}^n$ and there exist a vector not in the subspace spanned by the three vectors. However, nobody provide us the desired vector ourside of the subspace. We have to search for one now. One idea would be considering the standard basic vector $\mathbf{e}_i$ one by one. Here, along a popular idea in data science, we borrow probabilistic thinking: the subspace of dimension less than $n$ has a zero-volume in $\mathbb{R}^n$ and hence if we sample a vector randomly in $\mathbb{R}^n$, then it would be outside of the subspace with very high probability.

In [22]:
k = 3
Q = np.stack((v1,v2,v3),axis=1)

while k < n:
    a = np.random.randn(n)
    for i in range(k):
        a = a - np.inner(a,Q[:,i])*Q[:,i]
    if norm_scratch(a) > 1e-10:
        Q = np.concatenate((Q, (1/norm_scratch(a))*a[:,np.newaxis]), axis=1)
        k = k + 1

Surprisingly, the lines in the above cell is written down 100% by co-pilot!!!

In [23]:
print(Q)
print(Q.T @ Q)  # As you expect, it is an identity matrix of 10x10
print(Q @ Q.T)  # Now it is an identity matrix of 10x10

[[ 0.3666 -0.6032 -0.3203 -0.3003  0.2807 -0.1531 -0.0541 -0.0043 -0.4452 -0.075 ]
 [-0.3689  0.0236 -0.2551 -0.6493  0.0733  0.0821  0.0565 -0.4219  0.2413  0.3538]
 [ 0.0309  0.0047  0.2778 -0.1493  0.0358 -0.8164 -0.3977 -0.0118  0.2709  0.005 ]
 [ 0.1253  0.1922  0.4992 -0.4126 -0.4549  0.0456  0.0218 -0.176  -0.5342 -0.0448]
 [-0.2509 -0.3002 -0.3623  0.287  -0.7052 -0.161  -0.2005 -0.1042 -0.1312  0.2045]
 [ 0.4524  0.4613 -0.4236  0.1186 -0.0868 -0.2733  0.2715 -0.4558  0.0097 -0.159 ]
 [ 0.3192  0.1958 -0.2265 -0.1992 -0.1397  0.382  -0.7281  0.0989  0.1907 -0.1647]
 [ 0.3405 -0.4416  0.1812 -0.1542 -0.3698  0.11    0.3363 -0.031   0.5743 -0.1992]
 [ 0.3617  0.1774 -0.0982 -0.1277 -0.1191 -0.0809  0.1741  0.5305  0.0242  0.6919]
 [ 0.3109 -0.1758  0.3185  0.3457  0.1797  0.1899 -0.2186 -0.5292  0.0266  0.5046]]
[[ 1. -0. -0. -0. -0.  0. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.  0. -0.  0. -0.  0.]
 [-0. -0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  0.  1.  0.  0.  0.  0.  0.  0