# Chapter 4 $QR$-Decomposition

Let us investigate the inner products and projections in $\mathbf{R}^n$.

In [16]:
# numerical and scientific computing libraries  
import numpy as np 
import scipy as sp

# plotting libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
# for pretty printing
np.set_printoptions(4, linewidth=100, suppress=True)

### $QR$-Decomposition by Gram-Schmidt procedure

We define a function doing a naive $QR$-decomposition based on the Gram-Schmidt procedure to construct an upper triangular matrix $R$.

In [18]:
def classical_QR(A):
    m, n = A.shape

    R = np.zeros((n,n))
    R[0,0] = np.linalg.norm(A[:,0])

    Q = (1/R[0,0])*A[:,0]

    # Gram-Schmidt process
    for j in range(1,n):
        Q = np.column_stack((Q,A[:,j]))
        for i in range(j):
            R[i,j] = np.dot(Q[:,i].T,A[:,j])
            Q[:,j] = Q[:,j] - R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(Q[:,j])
        if np.abs(R[j,j]) < 1e-10:
            raise ValueError("QR factorization failed: A is rank deficient")  
    
        Q[:,j] = (1/R[j,j])*Q[:,j]

    return Q, R

Test the naive $QR$-decomposition for randomly generated matrix.

In [19]:
# Setting dimension m >= n 
m = 1000
n = 990

# Generating a random matrix A  of dimension m x n
A = np.random.randn(m,n)

Q, R = classical_QR(A)

# Checking the QR factorization
print(np.allclose(A,Q@R))
print(np.allclose(Q.T@Q,np.eye(n)))
print(R[:min(10,n),:min(10,n)])    

True
True
[[32.2746 -0.8268 -1.6879  0.7665 -0.6005  0.0149 -1.9404 -0.3694 -0.1131  1.1452]
 [ 0.     31.2441  0.7089  0.0482  0.8921  1.3735  1.446  -0.519   0.9768 -0.277 ]
 [ 0.      0.     30.8222  1.1871 -0.4396  1.425  -0.1451  0.0769 -0.1506  1.2231]
 [ 0.      0.      0.     31.1067  0.4292  1.0723  0.5361 -1.7488 -0.5323 -1.5206]
 [ 0.      0.      0.      0.     30.2069  1.0836  1.1266  0.6929  1.1381  2.046 ]
 [ 0.      0.      0.      0.      0.     30.5681 -0.1258 -0.4312 -0.2602 -1.7173]
 [ 0.      0.      0.      0.      0.      0.     32.0898  0.0614 -1.9422  0.7784]
 [ 0.      0.      0.      0.      0.      0.      0.     31.1149 -0.1366  0.7877]
 [ 0.      0.      0.      0.      0.      0.      0.      0.     31.1858 -0.7169]
 [ 0.      0.      0.      0.      0.      0.      0.      0.      0.     31.0399]]


An ill-conditioned example of $QR$-decomposition is the following.

In [22]:
A = np.array([[1, 1],
              [1e-8, 0],
              [0, 1e-8]], dtype=float)

Q, R = classical_QR(A)

print(np.allclose(A,Q@R))
print(np.allclose(Q.T@Q,np.eye(2)))
print(Q)
print(R)

True
True
[[ 1.      0.    ]
 [ 0.     -0.7071]
 [ 0.      0.7071]]
[[1. 1.]
 [0. 0.]]
