# Chapter 4 $QR$-Decomposition

Let us investigate the inner products and projections in $\mathbf{R}^n$.

In [2]:
# numerical and scientific computing libraries  
import numpy as np 
import scipy as sp

# plotting libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# for pretty printing
np.set_printoptions(4, linewidth=100, suppress=True)

### $QR$-Decomposition by Gram-Schmidt procedure

We define a function doing a naive $QR$-decomposition based on the Gram-Schmidt procedure to construct an upper triangular matrix $R$.

In [4]:
def classical_QR(A):
    m, n = A.shape

    R = np.zeros((n,n))
    R[0,0] = np.linalg.norm(A[:,0])

    Q = (1/R[0,0])*A[:,0]

    # Gram-Schmidt process
    for j in range(1,n):
        Q = np.column_stack((Q,A[:,j]))
        for i in range(j):
            R[i,j] = np.dot(Q[:,i].T,A[:,j])
            Q[:,j] = Q[:,j] - R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(Q[:,j])
        if np.abs(R[j,j]) < 1e-10:
            raise ValueError("QR factorization failed: A is rank deficient")  
    
        Q[:,j] = (1/R[j,j])*Q[:,j]

    return Q, R

Test the naive $QR$-decomposition for randomly generated matrix.

In [5]:
# Setting dimension m >= n 
m = 1000
n = 990

# Generating a random matrix A  of dimension m x n
A = np.random.randn(m,n)

Q, R = classical_QR(A)

# Checking the QR factorization
print(np.allclose(A,Q@R))
print(np.allclose(Q.T@Q,np.eye(n)))
print(R[:min(10,n),:min(10,n)])    

True
True
[[31.0728 -0.4599  1.5043  0.5618  1.3288  0.2266  0.9656 -1.6745 -0.4075  0.7667]
 [ 0.     30.2291  0.3661 -1.1778 -0.4924 -1.0276 -1.0851 -0.6622 -1.0277 -0.7064]
 [ 0.      0.     30.9592  1.3963 -1.1143  1.2984 -0.7342  1.795   0.2339  0.1418]
 [ 0.      0.      0.     32.986   1.5231  0.5362 -0.9628 -0.4111  0.0855 -0.4439]
 [ 0.      0.      0.      0.     30.8476  1.4517 -1.2405 -1.8453  0.7806 -0.057 ]
 [ 0.      0.      0.      0.      0.     29.9506  0.0669  0.1918 -0.0713 -0.7031]
 [ 0.      0.      0.      0.      0.      0.     31.529  -0.64   -0.4744  0.1873]
 [ 0.      0.      0.      0.      0.      0.      0.     32.3621 -0.9452  0.7793]
 [ 0.      0.      0.      0.      0.      0.      0.      0.     31.3604  0.2887]
 [ 0.      0.      0.      0.      0.      0.      0.      0.      0.     31.5441]]


However, this procedure fails for the following small ill-conditioned example. As a remedy for these ill-conditioned matrices, a modified one will be found in Chapter 5.

In [22]:

epsilon = 1e-8
A = np.array([[1, 1, 1],
              [epsilon, 0, 0],
              [0, epsilon, 0],
              [0, 0, epsilon]])

Q, R = classical_QR(A)

print(np.allclose(A,Q@R))
print(Q)
print(Q.T@Q)
print(R)

True
[[ 1.      0.      0.    ]
 [ 0.     -0.7071 -0.7071]
 [ 0.      0.7071  0.    ]
 [ 0.      0.      0.7071]]
[[ 1.  -0.  -0. ]
 [-0.   1.   0.5]
 [-0.   0.5  1. ]]
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
