# Chapter 4 $QR$-Decomposition

Let us investigate the inner products and projections in $\mathbf{R}^n$.

In [3]:
# numerical and scientific computing libraries  
import numpy as np 
import scipy as sp

# plotting libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# for pretty printing
np.set_printoptions(4, linewidth=100, suppress=True)

### $QR$-Decomposition by Gram-Schmidt procedure

We modify the Gram-Schmidt procedure to construct an upper triangular matrix $R$.

In [13]:
# Setting dimension m >= n 
m = 1000
n = 990

In [14]:
# Generating a random matrix A  of dimension m x n
A = np.random.randn(m,n)

R = np.zeros((n,n))
R[0,0] = np.linalg.norm(A[:,0])

Q = (1/R[0,0])*A[:,0]

# Gram-Schmidt process
for j in range(1,n):
    Q = np.column_stack((Q,A[:,j]))
    for i in range(j):
        R[i,j] = np.dot(Q[:,i].T,A[:,j])
        Q[:,j] = Q[:,j] - R[i,j]*Q[:,i]
    R[j,j] = np.linalg.norm(Q[:,j])
    Q[:,j] = (1/R[j,j])*Q[:,j]

# Checking the QR factorization
print(np.allclose(A,Q@R))
print(np.allclose(Q.T@Q,np.eye(n)))
print(R[:min(10,n),:min(10,n)])    

True
True
[[32.7791 -0.1179 -0.4452 -1.3331 -0.6591  0.6452 -1.8277  1.1891 -1.5439 -0.3207]
 [ 0.     32.1251  1.429  -1.6373  0.7497  0.605  -0.9694 -0.1793 -0.9345 -0.0175]
 [ 0.      0.     30.5784  0.5744 -1.4772  0.5784 -0.5911  0.8124 -1.6228 -0.8016]
 [ 0.      0.      0.     32.1499 -0.3595  0.2331  0.8883 -1.3065 -0.6194 -1.1465]
 [ 0.      0.      0.      0.     30.6813  1.0929 -1.868   1.0165  0.7516 -0.3965]
 [ 0.      0.      0.      0.      0.     30.6483  0.1156  1.2528 -2.5854  0.0988]
 [ 0.      0.      0.      0.      0.      0.     30.7676  0.5567 -0.1416  0.3742]
 [ 0.      0.      0.      0.      0.      0.      0.     30.7528  1.1148  0.5153]
 [ 0.      0.      0.      0.      0.      0.      0.      0.     30.9303 -0.5265]
 [ 0.      0.      0.      0.      0.      0.      0.      0.      0.     32.3309]]
