# Chapter 4 Euclidean Vector Spaces

Let us investigate the inner products and projections in $\mathbf{R}^n$.

In [3]:
# numerical and scientific computing libraries  
import numpy as np 
import scipy as sp

# plotting libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# for pretty printing
np.set_printoptions(4, linewidth=100, suppress=True)

### Standard inner product or dot product in $\mathbb{R}^n$.

For two Euclidean vectors $\mathbf{x}, \mathbf{y} \in \mathbb{R}^n$, we define the standard inner product or dot product as
$$\lang \mathbf{x}, \mathbf{y} \rang = \mathbf{x}^\top \mathbf{y} = \sum_{i=1}^n x_i y_i$$
Even though there are infinitely many inner products, as we have seen in the textbook, the standard inner product is a special one, on which our most numerics on the length and angle on the earth are based. Probably you might already encountered this concept (partially at least).

In [ ]:
# Setting dimension
n = 10
# two vectors generated randomly
a = np.random.randn(n)
b = np.random.randn(n)
print('a = ',a)
print('b = ',b)
# many ways of computing the dot product
ip1 = np.inner(a,b)
ip2 = np.dot(a,b)
ip3 = np.sum(a[:]*b[:])
ip4 = sum(a[:]*b[:])
# In principle, all these produce a single value. Be careful in using np.inner and np.dot when a and b are multi-dimensional.
print(ip1, ip2, ip3, ip4)

a =  [ 0.0188  1.5357 -1.265  -0.5935  0.9434 -0.1176  0.218   0.6629 -0.0479  0.9663]
b =  [-0.2884  0.7539  0.076   0.679   1.2687 -0.4188  0.3766 -0.3136 -0.7674  1.2819]
3.049017194508459 3.049017194508459 3.049017194508459 3.049017194508459


For a given inner product $\lang \cdot,\cdot\rang$, the associated norm of a vector $\mathbf{v}$ is defined as $|\mathbf{v}| = \sqrt{\lang \mathbf{v}, \mathbf{v} \rang}$. With the standard inner product, its norm or length is $|\mathbf{x}| = \sqrt{\mathbf{x}^\top \mathbf{x}}$.

In [ ]:
# Define a norm for standard inner product
def norm_scratch(v):
    return np.sqrt(sum(v**2))

print('|a| = ', norm_scratch(a), np.linalg.norm(a))
# normalize a vector
c = (1/norm_scratch(a))*a
print('|c| = ', norm_scratch(c))

|a| =  2.5764838452160315 2.5764838452160315
|c| =  1.0


**One-dimensional projection**

Now consider a one-dimensional projection along a vector $\mathbf{v}$.

In [13]:
v1 = np.random.randn(n)
norm_v1 = norm_scratch(v1)
v = (1/norm_v1)*v1

#check the unity of v
print(norm_scratch(v))

# project vector a along the direction of v
c1 = np.inner(a,v)
a_proj = c1*v
cosine = c1/norm_scratch(a)
print('angle = ', np.degrees(np.arccos(cosine)))

print('a      = ', a)
print('v      = ', v)
print('c1 = ', c1)
print('a_proj = ',a_proj)

0.9999999999999999
angle =  56.44887042622054
a      =  [ 0.0188  1.5357 -1.265  -0.5935  0.9434 -0.1176  0.218   0.6629 -0.0479  0.9663]
v      =  [ 0.3984  0.3739 -0.1279 -0.4656  0.1911 -0.3456 -0.3835  0.0553  0.313   0.2537]
c1 =  1.4239734309805592
a_proj =  [ 0.5673  0.5324 -0.1822 -0.6629  0.2721 -0.4921 -0.5461  0.0788  0.4457  0.3612]


**Gram-Schmidt procedure**



In [ ]:
a1 = np.random.randn(n)
a2 = np.random.randn(n)
a3 = np.random.randn(n)

# the first orthonormal vector
v1 = (1/norm_scratch(a1))*a1

# the second orthonormal vector
v = a2 - np.inner(a2,v1)*v1
v2 = (1/norm_scratch(v))*v

# the third orthonormal vector
v = a3 - np.inner(a3,v1)*v1 - np.inner(a3,v2)*v2
v3 = (1/norm_scratch(v))*v

# build a matrix of orthonormal vectors
Q = np.stack((v1,v2,v3),axis=1)

print(Q)
print(Q.T @ Q)  # As you expect, it is an identity matrix of 3x3
print(Q @ Q.T)  # It is meaningless matrix of 10x10

[[ 0.2445 -0.3147  0.4247]
 [-0.1913 -0.2672  0.3137]
 [ 0.1006  0.2762 -0.1445]
 [-0.5884  0.6128  0.2478]
 [-0.2956  0.0618  0.1403]
 [ 0.0332 -0.1237  0.1615]
 [-0.1667 -0.1247 -0.5849]
 [ 0.6216  0.4649 -0.0085]
 [-0.1684 -0.339   0.0217]
 [ 0.1281  0.1102  0.5006]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.3391  0.1705 -0.1237 -0.2314 -0.0321  0.1156 -0.2499  0.002   0.0747  0.2092]
 [ 0.1705  0.2064 -0.1384  0.0265  0.084   0.0774 -0.1182 -0.2458  0.1296  0.1031]
 [-0.1237 -0.1384  0.1073  0.0743 -0.0329 -0.0542  0.0333  0.1921 -0.1137 -0.029 ]
 [-0.2314  0.0265  0.0743  0.7831  0.2465 -0.0553 -0.1233 -0.083  -0.1033  0.1163]
 [-0.0321  0.084  -0.0329  0.2465  0.1109  0.0052 -0.0405 -0.1562  0.0319  0.0392]
 [ 0.1156  0.0774 -0.0542 -0.0553  0.0052  0.0425 -0.0846 -0.0382  0.0398  0.0715]
 [-0.2499 -0.1182  0.0333 -0.1233 -0.0405 -0.0846  0.3854 -0.1566  0.0576 -0.3279]
 [ 0.002  -0.2458  0.1921 -0.083  -0.1562 -0.0382 -0.1566  0.6025 -0.2624  0.1266]
 [ 0.0747  0.1296 -0.1137 -0

Now let us go further to find a orthonormal basis of $\mathbb{R}^{10}$.