# Chapter 4 Euclidean Vector Spaces

Let us investigate the inner products and projections in $\mathbf{R}^n$.

In [3]:
# numerical and scientific computing libraries  
import numpy as np 
import scipy as sp

# plotting libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# for pretty printing
np.set_printoptions(4, linewidth=100, suppress=True)

### Standard inner product or dot product in $\mathbb{R}^n$.

For two Euclidean vectors $\mathbf{x}, \mathbf{y} \in \mathbb{R}^n$, we define the standard inner product or dot product as
$$<\mathbf{x}, \mathbf{y}> = \mathbf{x}^\top \mathbf{y} = \sum_{i=1}^n x_i y_i$$
Even though there are infinitely many inner products, as we have seen in the textbook, the standard inner product is a special one, on which our most numerics on the length and angle on the earth are based. Probably you might already encountered this concept (partially at least).

In [44]:
# Setting dimension
n = 10

In [45]:
# two vectors generated randomly
a = np.random.randn(n)
b = np.random.randn(n)
print('a = ',a)
print('b = ',b)
# many ways of computing the dot product
ip1 = np.inner(a,b)
ip2 = np.dot(a,b)
ip3 = np.sum(a[:]*b[:])
ip4 = sum(a[:]*b[:])
# In principle, all these produce a single value. Be careful in using np.inner and np.dot when a and b are multi-dimensional.
print(ip1, ip2, ip3, ip4)

a =  [ 0.0672  0.048  -0.029   1.1152  0.5597 -0.074  -0.2288 -0.3743  1.35    0.2169]
b =  [ 0.367   0.6792  0.7419 -1.0125 -0.5873  0.7989  0.9749 -2.6531 -1.3734 -0.9072]
-2.7620943477595925 -2.7620943477595925 -2.7620943477595925 -2.762094347759592


For a given inner product $<\cdot,\cdot>$, the associated norm of a vector $\mathbf{v}$ is defined as $|\mathbf{v}| = \sqrt{<\mathbf{v}, \mathbf{v}>}$. With the standard inner product, its norm or length is $|\mathbf{x}| = \sqrt{\mathbf{x}^\top \mathbf{x}}$.

In [46]:
# Define a norm for standard inner product
def norm_scratch(v):
    return np.sqrt(sum(v**2))

print('|a| = ', norm_scratch(a), np.linalg.norm(a))
# normalize a vector
c = (1/norm_scratch(a))*a
print('|c| = ', norm_scratch(c))

|a| =  1.905818636783195 1.905818636783195
|c| =  1.0


**One-dimensional projection**

Now consider a one-dimensional projection along a vector $\mathbf{v}$.

In [48]:
v1 = np.random.randn(n)
norm_v1 = norm_scratch(v1)
v = (1/norm_v1)*v1

#check the unity of v
print(norm_scratch(v))

# project vector a along the direction of v
c1 = np.inner(a,v)
a_proj = c1*v
cosine = c1/norm_scratch(a)
print('angle = ', np.degrees(np.arccos(cosine)))

print('a      = ', a)
print('v      = ', v)
print('c1 = ', c1)
print('a_proj = ',a_proj)

0.9999999999999999
angle =  106.87119655132207
a      =  [ 0.0672  0.048  -0.029   1.1152  0.5597 -0.074  -0.2288 -0.3743  1.35    0.2169]
v      =  [-0.4304 -0.4212  0.0719  0.0622 -0.593   0.2492  0.2723 -0.3008 -0.1795 -0.1328]
c1 =  -0.5531088808981259
a_proj =  [ 0.2381  0.233  -0.0398 -0.0344  0.328  -0.1378 -0.1506  0.1664  0.0993  0.0735]


**Gram-Schmidt procedure**



In [55]:
# Setting dimension
n = 10

In [56]:
a1 = np.random.randn(n)
a2 = np.random.randn(n)
a3 = np.random.randn(n)

# the first orthonormal vector
v1 = (1/norm_scratch(a1))*a1

# the second orthonormal vector
v = a2 - np.inner(a2,v1)*v1
v2 = (1/norm_scratch(v))*v

# the third orthonormal vector
v = a3 - np.inner(a3,v1)*v1 - np.inner(a3,v2)*v2
v3 = (1/norm_scratch(v))*v

# build a matrix of orthonormal vectors
Q = np.stack((v1,v2,v3),axis=1)

print(Q)
print(Q.T @ Q)  # As you expect, it is an identity matrix of 3x3
print(Q @ Q.T)  # It is meaningless matrix of 10x10

[[-0.0399 -0.4094 -0.0293]
 [ 0.2972 -0.0212 -0.3281]
 [-0.012   0.1363  0.2737]
 [ 0.134   0.337  -0.2834]
 [ 0.4604  0.1595  0.6304]
 [ 0.4559 -0.1455  0.0984]
 [ 0.3304  0.5502 -0.3612]
 [-0.068  -0.3564 -0.068 ]
 [ 0.4396 -0.2202  0.1824]
 [ 0.4062 -0.4182 -0.401 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.1701  0.0065 -0.0633 -0.135  -0.1021  0.0385 -0.2279  0.1506  0.0673  0.1668]
 [ 0.0065  0.1965 -0.0963  0.1257 -0.0734  0.1063  0.2051  0.0096  0.0755  0.2612]
 [-0.0633 -0.0963  0.0936 -0.0333  0.1887  0.0016 -0.0278 -0.0663  0.0146 -0.1716]
 [-0.135   0.1257 -0.0333  0.2119 -0.0632 -0.0158  0.3321 -0.11   -0.067   0.0272]
 [-0.1021 -0.0734  0.1887 -0.0632  0.6348  0.2487  0.0122 -0.131   0.2823 -0.1325]
 [ 0.0385  0.1063  0.0016 -0.0158  0.2487  0.2387  0.0351  0.0141  0.2504  0.2066]
 [-0.2279  0.2051 -0.0278  0.3321  0.0122  0.0351  0.5424 -0.194  -0.0418  0.0489]
 [ 0.1506  0.0096 -0.0663 -0.11   -0.131   0.0141 -0.194   0.1363  0.0362  0.1487]
 [ 0.0673  0.0755  0.0146 -0

In [57]:
# Example for 3D visualization (if n=3)
if n==3:
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    # Plot original vectors
    ax.quiver(0, 0, 0, a1[0], a1[1], a1[2], color='r', label='a1')
    ax.quiver(0, 0, 0, a2[0], a2[1], a2[2], color='g', label='a2')
    ax.quiver(0, 0, 0, a3[0], a3[1], a3[2], color='b', label='a3')

    # Plot orthonormal vectors
    ax.quiver(0, 0, 0, v1[0], v1[1], v1[2], color='c', label='v1 (orthonormal)')
    ax.quiver(0, 0, 0, v2[0], v2[1], v2[2], color='m', label='v2 (orthonormal)')
    ax.quiver(0, 0, 0, v3[0], v3[1], v3[2], color='y', label='v3 (orthonormal)')

    ax.set_xlim([-2, 2])
    ax.set_ylim([-2, 2])
    ax.set_zlim([-2, 2])
    ax.legend()
    plt.show()

For $n > 3$, let us go further to find a orthonormal basis of $\mathbb{R}^n$. In the textbook, three vectors can not span $\mathbb{R}^n$ and there exist a vector not in the subspace spanned by the three vectors. However, nobody provide us the desired vector ourside of the subspace. We have to search for one now. One idea would be considering the standard basic vector $\mathbf{e}_i$ one by one. Here, along a popular idea in data science, we borrow probabilistic thinking: the subspace of dimension less than $n$ has a zero-volume in $\mathbb{R}^n$ and hence if we sample a vector randomly in $\mathbb{R}^n$, then it would be outside of the subspace with very high probability.

In [58]:
k = 3
Q = np.stack((v1,v2,v3),axis=1)

while k < n:
    a = np.random.randn(n)
    for i in range(k):
        a = a - np.inner(a,Q[:,i])*Q[:,i]
    if norm_scratch(a) > 1e-10:
        Q = np.concatenate((Q, (1/norm_scratch(a))*a[:,np.newaxis]), axis=1)
        k = k + 1

Surprisingly, the lines in the above cell is written down 100% by co-pilot!!!

In [59]:
print(Q)
print(Q.T @ Q)  # As you expect, it is an identity matrix of 10x10
print(Q @ Q.T)  # Now it is an identity matrix of 10x10

[[-0.0399 -0.4094 -0.0293  0.2372  0.6643 -0.0705  0.3733 -0.0405  0.4224  0.0892]
 [ 0.2972 -0.0212 -0.3281  0.5763 -0.1809  0.6279 -0.097  -0.1192  0.1034  0.1006]
 [-0.012   0.1363  0.2737  0.394   0.0393 -0.3888 -0.4753 -0.036   0.0914  0.6024]
 [ 0.134   0.337  -0.2834  0.0692 -0.2465 -0.4353  0.2834 -0.5845  0.3133 -0.1138]
 [ 0.4604  0.1595  0.6304 -0.232   0.1222  0.2695 -0.1321 -0.2291  0.3549 -0.1674]
 [ 0.4559 -0.1455  0.0984  0.199  -0.3564 -0.3154  0.2123  0.6227  0.2066 -0.1398]
 [ 0.3304  0.5502 -0.3612 -0.2925  0.3628  0.0643  0.1013  0.3186  0.0103  0.3527]
 [-0.068  -0.3564 -0.068  -0.4669 -0.4063  0.1525  0.1016 -0.0552  0.356   0.5633]
 [ 0.4396 -0.2202  0.1824  0.0207  0.0203 -0.0706  0.379  -0.2841 -0.6389  0.2942]
 [ 0.4062 -0.4182 -0.401  -0.2328  0.1565 -0.2359 -0.5642 -0.1252 -0.0264 -0.1739]]
[[ 1.  0.  0.  0. -0.  0.  0. -0. -0.  0.]
 [ 0.  1.  0.  0.  0. -0.  0.  0. -0. -0.]
 [ 0.  0.  1.  0. -0.  0.  0. -0. -0. -0.]
 [ 0.  0.  0.  1. -0.  0.  0. -0.  0. -0