# Chapter 7 Positive Definite Matrices

Let us investigate positive definiteness of matrices.

In [2]:
# numerical and scientific computing libraries  
import numpy as np 
import scipy as sp

# plotting libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# for pretty printing
np.set_printoptions(4, linewidth=100, suppress=True)

### Positive definite matrices


In [27]:
# Setting dimension
n = 10

In [28]:
# two vectors generated randomly
B_pd = np.random.randn(n,n)
A_pd = B_pd.T @ B_pd
# compute compact svd decomposition of A
U, s, Vt = np.linalg.svd(A_pd, full_matrices=False)
V = Vt.T
# compute the rank of A
rank_A = sum(s > 1e-10)
# print svd decomposition with its rank
print(f"rank of A: {rank_A}")
print('s = ')
print(s)
print('U = ')
print(U)
print('V = ')
print(V)

rank of A: 10
s = 
[20.685  16.9876 15.2428  9.776   5.8343  4.7799  2.3722  1.1936  0.1901  0.0194]
U = 
[[-0.6544 -0.1475  0.1018  0.1874 -0.1804 -0.0099 -0.3188 -0.5152 -0.2111 -0.2455]
 [ 0.2469 -0.0154  0.632   0.021   0.0933  0.0193 -0.4622 -0.1485  0.5423  0.0055]
 [-0.2621  0.0219  0.4129 -0.6883  0.2262 -0.3062  0.0111  0.1366 -0.3173  0.1491]
 [-0.0158  0.1971  0.2499  0.009  -0.0173  0.7671 -0.1778  0.3466 -0.3581 -0.1723]
 [ 0.5    -0.1263 -0.209  -0.2635  0.329   0.0002 -0.187  -0.3777 -0.2917 -0.5   ]
 [-0.1323  0.0743 -0.2563  0.1859  0.1988 -0.3741 -0.5756  0.5632 -0.0013 -0.2207]
 [ 0.0413  0.4986 -0.0692  0.2718  0.4409  0.0013 -0.1792 -0.3057 -0.2523  0.5361]
 [ 0.2753  0.4303 -0.0394 -0.191  -0.7382 -0.2043 -0.271  -0.0759 -0.1778  0.0604]
 [ 0.1714  0.1537  0.4824  0.4869  0.0097 -0.3664  0.3638  0.0735 -0.3099 -0.3303]
 [ 0.26   -0.6781  0.0937  0.1977 -0.142  -0.0381 -0.221   0.0964 -0.3951  0.4346]]
V = 
[[-0.6544 -0.1475  0.1018  0.1874 -0.1804 -0.0099 -0.3188 

We can see that all singular values are positive, and $U=V$ which are eigenvectors of $A$ with singular values as their eigenvalues.

### Positive semi-definite matrices

In [29]:
k = 7
B_psd = np.random.randn(n,k)
A_psd = B_psd @ B_psd.T
# compute compact svd decomposition of A
U, s, Vt = np.linalg.svd(A_psd, full_matrices=False)
V = Vt.T
# compute the rank of A
rank_A = sum(s > 1e-10)
# print svd decomposition with its rank
print(f"rank of A: {rank_A}")
print('s = ')
print(s)
print('U = ')
print(U)
print('V = ')
print(V)

rank of A: 7
s = 
[18.6081 13.4608 10.2833  8.5961  7.0617  1.2762  0.204   0.      0.      0.    ]
U = 
[[-0.5307  0.4369 -0.0923  0.4954 -0.145   0.0602  0.0229 -0.3735 -0.1361 -0.3005]
 [-0.2849  0.1564  0.6743 -0.3722 -0.239   0.0995  0.2079 -0.2123 -0.0978  0.3691]
 [ 0.2407 -0.4491  0.065   0.258  -0.192   0.5343  0.4491 -0.3094  0.178  -0.1347]
 [ 0.117   0.2032  0.4155 -0.0964  0.455  -0.1449  0.3534  0.1188  0.1147 -0.6188]
 [-0.4517 -0.1671 -0.3003 -0.167  -0.3059 -0.2646  0.5412  0.3671  0.236  -0.0555]
 [-0.4186 -0.4706 -0.0051  0.117   0.6478 -0.0405  0.1188 -0.1161 -0.304   0.2197]
 [-0.3241  0.0355  0.1165  0.0669  0.2314  0.3179 -0.3059  0.1355  0.7729  0.1085]
 [-0.1287 -0.2086 -0.2209 -0.5906 -0.0114 -0.0882 -0.23   -0.5803  0.1401 -0.3537]
 [-0.2401 -0.1357  0.0474 -0.2157 -0.1173  0.5543 -0.2444  0.4465 -0.3991 -0.3684]
 [ 0.0843  0.4786 -0.4528 -0.3144  0.312   0.4384  0.3413 -0.0529 -0.0514  0.22  ]]
V = 
[[-0.5307  0.4369 -0.0923  0.4954 -0.145   0.0602  0.0229  

Now $A$ is non-invertible and has 7 singular values. Therefore, $A$ has 3 eigenvalues of 0, and the corresponding right- and left-singular vectors may not be the same to each other. This happens in the above experiment. In Section 5.5 of the textbook, we show that we can make them coincide to control the one-dimensional optimization problem.

### Cholesky decomposition

We have to find an upper triangular $R$ with positive diagonals and $A = R^\top R$.

In [30]:
A = A_pd
# compute the cholesky decomposition of A
R = np.zeros((n,n))
for i in range(n):
    R[i,i] = np.sqrt(A[i,i] - np.dot(R[:i,i], R[:i,i]))
    for j in range(i+1,n):
        R[i,j] = (A[i,j]-np.dot(R[:i,i],R[:i,j])) / R[i,i]

# invoke numpy's cholesky decomposition
R1 = np.linalg.cholesky(A_pd, upper=True)
# compare the two results
print(np.allclose(R, R1))

True


In the textbook, we have also seen that the upper triangular cholesky factor coincides with $R$ of $B=QR$ where $A = B^\top B$. Let us check this fact. The uniqueness of Cholesky factor makes this comparison feasible. 

In $QR$-decomposition, as we mentioned in the textbook, we can always make the diagonals of $R$ positive. The following codes includes such modification in the last three lines.

In [36]:
# classical QR factorization with positive diagonals
def classical_QR_pdiag(A):
    m, n = A.shape

    R = np.zeros((n,n))
    R[0,0] = np.linalg.norm(A[:,0])

    Q = (1/R[0,0])*A[:,0]

    # Gram-Schmidt process
    for j in range(1,n):
        Q = np.column_stack((Q,A[:,j]))
        for i in range(j):
            R[i,j] = np.dot(Q[:,i].T,A[:,j])
            Q[:,j] = Q[:,j] - R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(Q[:,j])
        if np.abs(R[j,j]) < 1e-10:
            raise ValueError("QR factorization failed: A is rank deficient")  
    
        Q[:,j] = (1/R[j,j])*Q[:,j]

    D = np.diag(np.sign(R.diagonal()))
    Q = Q @ D
    R = D @ R
    
    return Q, R

In [37]:
Q2, R2 = classical_QR_pdiag(B_pd)
# compare the two results
print(np.allclose(R, R2))

True


### Square root of positive definte matrices

As we can see in the following codes, SVD provides the square root of a positive definite matrix.

In [44]:
# compute compact svd decomposition of A_pd
U, s, Vt = np.linalg.svd(A_pd, full_matrices=False)
V = Vt.T
# compute the rank of A_pd
rank_A = sum(s > 1e-10)
# print svd decomposition with its rank
print(f"rank of A_pd: {rank_A}")
print('s = ', s)

if np.allclose(U,V):
    print('U=V')

# set B = V @ np.diag(np.sqrt(s)) @ U.T
B = V @ np.diag(np.sqrt(s)) @ V.T

if np.allclose(A_pd, B@B):
    print('A = B^2')
if np.allclose(A_pd, B.T @ B):
    print('A = B^T B')

rank of A_pd: 10
s =  [20.685  16.9876 15.2428  9.776   5.8343  4.7799  2.3722  1.1936  0.1901  0.0194]
U=V
A = B^2
A = B^T B
