# Chapter 9 Eigenvalues

In [2]:
# numerical and scientific computing libraries 
import numpy as np
import scipy as sp

# plotting libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# for pretty printing
np.set_printoptions(4, linewidth=100, suppress=True)

In [4]:
# set dimension
n = 10

In [6]:
# create a random matrix
A = np.random.randn(n,n)
# eigenpairs
value, vectors = sp.linalg.eig(A)

print('eigenvalues  = ', value)
print('eigenvectors = ')
print(vectors)

print(np.allclose(A @ vectors, vectors @ np.diag(value)))

eigenvalues  =  [ 2.5415+0.j      1.8663+1.7707j  1.8663-1.7707j -2.1816+1.8801j -2.1816-1.8801j  0.1199+1.8417j
  0.1199-1.8417j  0.2777+0.j     -1.1589+0.j     -1.348 +0.j    ]
eigenvectors = 
[[-0.2651+0.j      0.0617-0.1517j  0.0617+0.1517j  0.056 -0.3225j  0.056 +0.3225j  0.5283+0.j
   0.5283-0.j      0.2142+0.j     -0.2741+0.j      0.2992+0.j    ]
 [-0.5868+0.j      0.2557-0.081j   0.2557+0.081j   0.2494-0.0002j  0.2494+0.0002j -0.2463+0.1153j
  -0.2463-0.1153j -0.6317+0.j      0.0904+0.j     -0.0252+0.j    ]
 [-0.4173+0.j      0.0699+0.3676j  0.0699-0.3676j  0.1693-0.1324j  0.1693+0.1324j  0.1379-0.0953j
   0.1379+0.0953j -0.2914+0.j     -0.5672+0.j      0.6909+0.j    ]
 [-0.1884+0.j     -0.0047+0.21j   -0.0047-0.21j    0.1475-0.0424j  0.1475+0.0424j  0.0605+0.0988j
   0.0605-0.0988j  0.3552+0.j      0.0694+0.j     -0.2403+0.j    ]
 [-0.072 +0.j     -0.5402+0.j     -0.5402-0.j     -0.0363-0.1995j -0.0363+0.1995j -0.0636+0.0241j
  -0.0636-0.0241j -0.2626+0.j     -0.1195+0.j      

We can see complex eigenvalues and eigenvecrors in most random instances. Let us try symmetric matrices as we already proved that the symmetric ones have only real eigenpairs.

In [8]:
# create a random matrix
A = np.random.randn(n,n)
A = A + A.T
# eigenpairs
value, vectors = sp.linalg.eig(A)

print('eigenvalues  = ', value)
print('eigenvectors = ')
print(vectors)

print(np.allclose(A @ vectors, vectors @ np.diag(value)))

eigenvalues  =  [-7.1716+0.j  6.3868+0.j  5.2061+0.j -4.5403+0.j -3.7391+0.j -2.5717+0.j  3.097 +0.j  1.5905+0.j
  0.3632+0.j -0.6592+0.j]
eigenvectors = 
[[-0.4018 -0.2919  0.0314  0.2129  0.5342 -0.5393 -0.1866 -0.0249 -0.3086  0.0121]
 [-0.7117  0.2001  0.1551  0.0185 -0.1795  0.2843  0.4241 -0.0341 -0.2863  0.2303]
 [ 0.1419  0.272   0.437   0.3158  0.0534 -0.3472  0.3393 -0.4883  0.3578  0.1007]
 [-0.0216  0.1663 -0.4324 -0.3379 -0.0188 -0.2352  0.3286 -0.3974 -0.2159 -0.55  ]
 [ 0.0382  0.2814  0.0342 -0.3774 -0.2642 -0.2382 -0.4843 -0.3464 -0.2747  0.4681]
 [ 0.16   -0.0873  0.1712  0.3483 -0.6347 -0.3616  0.0651  0.2713 -0.404  -0.2035]
 [-0.0976  0.7899 -0.177   0.3508  0.1484  0.0029 -0.2939  0.2525  0.0052 -0.2   ]
 [ 0.3976 -0.0341 -0.277   0.4409  0.1963  0.3338  0.1256 -0.3035 -0.4942  0.2599]
 [ 0.286   0.2211 -0.0374 -0.3124  0.2623 -0.294   0.4617  0.5023 -0.1386  0.361 ]
 [-0.1871 -0.1112 -0.676   0.2483 -0.2778 -0.2589  0.0897  0.0112  0.382   0.3684]]
True


We confirm the real spectral decomposition theorem. 